### PR TITLE
exposes opts + bits

### PR DESCRIPTION
**Pull request by noffle**

### CODE REVIEW

**Comment by nginnever** [comment]
LGTM

**Comment by diasdavid** [comment]
thank you @noffle . Could you add a test with this PR?

**Comment by nginnever** [comment]
Is it possible to supply less than 1024 or a non-scalar value of bits to this? I remember seeing this in go where they require the bits to at least be greater than 1024 as well as some tests that ensure it's multiple of 1024.

https://github.com/ipfs/go-ipfs/blob/6f8ea136d5d9d927016c59a232b712e7bd6ba795/repo/config/init.go#L92**

**Comment by noffle** [comment]
@diasdavid: Added a test. It's not very rigorous, but you aren't guaranteed a certain # of bytes in the resultant private key -- it varies from key to key.

@nginnever: You can generate smaller keys (it would seem). go-ipfs puts that limit for security, but I think that should be an IPFS-level concern (application) rather than a library concern.

**Comment by diasdavid** [comment]
LGTM, thank you @noffle and @nginnever for the input! :)

**Comment by diasdavid** [comment]
released on 0.6.1 :)

**Pull request merged**
